version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000" 
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://intercom@postgres/intercom
  postgres:
    ports:
      - "5432:5432" 
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: intercom
      POSTGRES_DB: intercom